### ISSUE TITLE
Horizontal alignment - center

### ISSUE THREAD

**Issue by BrenoVin** [mischa-hildebrand/AlignedCollectionViewFlowLayout#10]
That's any way to align the item centralized in the horizontalAlignment ?

**Comment by mischa-hildebrand** [comment]
Unfortunately, I see no way to achieve this properly with the current approach that the library uses.

For detailed information, see → [pull request "horizontalAlignment.center"](https://github.com/mischa-hildebrand/AlignedCollectionViewFlowLayout/pull/2).
