### ISSUE TITLE
crash in 9iOS 

### ISSUE THREAD

**Issue by VizenkoRoman** [mischa-hildebrand/AlignedCollectionViewFlowLayout#19]
This example with iOS 9 has crash

**Comment by wintersmoon** [comment]
I also got crash using this layout file in iOS9.
It crashed in override func layoutAttributesForElements(in: rect).

**Comment by mischa-hildebrand** [comment]
As the current version is iOS 12, I won't make the effort to fix issues that occur on iOS 9 (due to limited time). However, if you manage to identify and fix the problem, I welcome any pull requests.
