### ISSUE TITLE
Horizontal scrolling in single line

### ISSUE THREAD

**Issue by vincenzo-favara** [mischa-hildebrand/AlignedCollectionViewFlowLayout#25]
Is there a way to edit the flow layout to have a single line scrolling horizontally?

**Comment by mischa-hildebrand** [comment]
No.

The single problem this library tries to solve is the alignment of cells which cannot be accomplished with Apple's default flow layout. For other problems you'll have to look for other tools. (I don't see how a single line layout is related to aligning cells in rows.)
