### ISSUE TITLE
Pod updated to 1.1.1?

### ISSUE THREAD

**Issue by chadbag** [mischa-hildebrand/AlignedCollectionViewFlowLayout#3]
When will the pod be updated?  The pod still has the issue of the init being "internal" and therefore inaccessible to users of the pod.

**Comment by mischa-hildebrand** [comment]
I have updated the pod as well. Maybe it took some time to process. Can you please check again?

In the (parsed) documentation the initializer is visible already which means it must be public:
http://cocoadocs.org/docsets/AlignedCollectionViewFlowLayout/1.1.1/Classes/AlignedCollectionViewFlowLayout.html

**Comment by chadbag** [comment]
My pod file says

  pod 'AlignedCollectionViewFlowLayout'


And I get 1.1.0 with the problem on init

"initializer is inaccessible due to 'internall' protection level"

or something like that.

Btw, this is a really nice effort!

**Comment by mischa-hildebrand** [comment]
Thanks! I've just created a brand new Xcode project and added a podfile with `pod "AlignedCollectionViewFlowLayout"` as its only pod and ran `pod install`. Works for me.

It installs version 1.1.1 with the public initializer.

Please make sure you run `pod update` and not `pod install`.

**Comment by chadbag** [comment]
I got it working now.  I thought I had done "pod update" at first but I must have done "pod install" out of habit.   When I add a new pod I try and remember the update...

**Comment by mischa-hildebrand** [comment]
Awesome. I'll close this issue.

(Generally, you don't need to run `pod update` when you add a new pod. In that case `pod install` is sufficient. You only need `pod update` in case you have an older version of a pod installed and want to update that pod to a higher version.)
