### ISSUE TITLE
How to prevent cells from being wider than the collection view?

### ISSUE THREAD

**Issue by groue** [mischa-hildebrand/AlignedCollectionViewFlowLayout#34]
Hello @mischa-hildebrand,

I could not figure how to limit the width of cells, so that they do not extend the width of the enclosing collection view.

Do you have any advice ?

In the screenshot below, UILabels have the standard compression resistance, have `lineBreakMode = .byTruncatingTail`, and `numberOfLines = 1`:

<img width="549" alt="Capture d’écran 2021-06-23 à 12 05 13 - copie" src="https://user-images.githubusercontent.com/54219/123078546-5fb78400-d41b-11eb-8a03-6721cac17e35.png">

**Comment by i-Senku** [comment]
@groue did you fix that? if you did can you share your solution?

**Comment by groue** [comment]
Hello @i-Senku,

I did not fixed this. I stopped using this library, and implemented by own UIView. Code is not released publicly, unfortunately.

**Comment by i-Senku** [comment]
@groue i fixed. You need to set property `preferredMaxLayoutWidth`  of UILabel.
 for example: `testLabel.preferredMaxLayoutWidth = UIScreen.main.bounds * 0.8`

<img src= "https://user-images.githubusercontent.com/54575884/166266319-d909e1ae-331c-4f3b-ba01-0fdbec046253.jpeg" width="400">

**Comment by groue** [comment]
We did not have the same goal :-) You wanted a multiline label, I wanted a truncated (`…`) label. Anyway, thanks for your solution, we can close this issue.

**Comment by i-Senku** [comment]
@groue in my case numberOfLines = 0 if i set 1 it will look like truncated 😅
