### ISSUE TITLE
左对齐，内容过长超出屏幕外。

### ISSUE THREAD

**Issue by ITzhao** [mischa-hildebrand/AlignedCollectionViewFlowLayout#36]
init（horizontalAlignment：.left，verticalAlignment：.top）

估计项目尺寸=CGSize（宽度：100，高度：40）

cell 内容过长，超出屏幕外

应该处理成 ... 省略模式

**Comment by mischa-hildebrand** [comment]
Sorry, I know a tiny bit of Chinese, but not that much... 😅 

Please open another issue in English.
