### ISSUE TITLE
Add Natural horizontal alignment.

### ISSUE THREAD

**Issue by lhunath** [mischa-hildebrand/AlignedCollectionViewFlowLayout#8]
Given that for some layouts the desired alignment of the cells may actually depend upon how the cells themselves align their content with respect to the leading and trailing edges or depending upon their labels' text alignment, it makes sense to be directionally aware in this library.

**Comment by mischa-hildebrand** [comment]
That's a great idea!

To be clear: You're suggesting to add `.leading` and `.trailing` as `HorizontalAlignment` options?

(I think it's not a big thing to implement that yourself in your app but it might be a nice convenience feature for the library.)

**Comment by lhunath** [comment]
Yeah, I'm not 100% sure if it makes most sense to model it after `NSTextAlignment` or `NSLayoutConstraint.Attribute`.

**Comment by yonat** [comment]
Another option is `UIControlContentHorizontalAlignment`.

**Comment by lhunath** [comment]
Yes, it wouldn't be crazy to adopt perhaps this enum as opposed to making your own.  Though there is a `fill` here too.  Which.. maybe isn't crazy?

**Comment by lhunath** [comment]
Again though, I'm not sure exactly when it makes more sense to think in terms of a single attribute akin to `NSTextAlignment.natural` as opposed to explicitly picking a `.leading` vs. `.trailing`.  My intuition tells me the latter makes most sense and `UIControlContentHorizontalAlignment` is perhaps very close to what works best.  But I'm just not sure under what conditions it makes more sense to think in terms of a single "natural" attribute.

**Comment by mischa-hildebrand** [comment]
I just merged a [pull request](https://github.com/mischa-hildebrand/AlignedCollectionViewFlowLayout/pull/20) from @e-sung that introduces `.leading` and  `.trailing` as additional `Alignment` attributes.

It might not be exactly what you wished for, but there are some reasons why I don't want to use the existing `NSTextAlignment` type. The most important is that I only want to provide options to the developer that this library actually supports. As of today, `AlignedCollectionViewFlowLayout` does not support a `center` alignment, so using this attribute would lead to a crash or unexpected behavior. The same goes for `UIControlContentHorizontalAlignment`.

@lhunath, are you okay with this solution or do I miss something important?

**Comment by lhunath** [comment]
This is probably good!

**Comment by mischa-hildebrand** [comment]
Awesome, then I'll close this issue.
